# -*- coding: utf-8 -*-
"""ai_health.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tZBqxXnXVzTFFF5rH4lhLwJIA1GZsjQL
"""

!pip install pandas numpy scikit-learn matplotlib seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, r2_score

rain_df = pd.read_csv("/content/Dataset/e5c275eb-a4f2-4412-9677-73654e8f5f4d.csv")
soil_df = pd.read_csv("/content/Dataset/sm_Tamilnadu_2020.csv")

rain_df["Date"] = pd.to_datetime(rain_df["Date"], dayfirst=True, errors="coerce")

rain_df = rain_df[rain_df["Date"].dt.year == 2020]

rain_df["Rainfall"] = pd.to_numeric(rain_df["Rainfall"], errors="coerce")

rain_daily = (
    rain_df.groupby("Date")["Rainfall"]
    .mean()
    .reset_index()
)

soil_df["Date"] = pd.to_datetime(soil_df["Date"], errors="coerce")

soil_df = soil_df[soil_df["DistrictName"].str.upper() == "CHENNAI"]

soil_daily = soil_df[[
    "Date",
    "Volume Soilmoisture percentage (at 15cm)"
]].copy()

soil_daily.rename(
    columns={
        "Volume Soilmoisture percentage (at 15cm)": "Soil_Moisture"
    },
    inplace=True
)

df = pd.merge(rain_daily, soil_daily, on="Date", how="inner")
df = df.sort_values("Date").reset_index(drop=True)

print(df.head())
print(len(df))

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df["Soil_Sat"] = scaler.fit_transform(df[["Soil_Moisture"]])

df["Rain_3day"] = df["Rainfall"].rolling(3).sum()
df["Rain_7day"] = df["Rainfall"].rolling(7).sum()
df["Effective_Rain"] = df["Rainfall"] * df["Soil_Sat"]

df["Runoff"] = 0.0

for i in range(1, len(df)):
    df.loc[i, "Runoff"] = (
        0.7 * df.loc[i, "Effective_Rain"] +
        0.3 * df.loc[i-1, "Runoff"]
    )

df["Drain_Level"] = (
    0.6 * df["Runoff"] +
    0.4 * df["Rain_3day"]
)
df["Drain_Level_Norm"] = scaler.fit_transform(df[["Drain_Level"]])

df["Rain_3day_Norm"] = scaler.fit_transform(df[["Rain_3day"]])

df["Stress_Index"] = (
    0.5 * df["Rain_3day_Norm"] +
    0.3 * df["Soil_Sat"] +
    0.2 * df["Drain_Level_Norm"]
)

df = df.dropna().reset_index(drop=True)

import matplotlib.pyplot as plt

plt.figure(figsize=(12,5))
plt.plot(df["Date"], df["Runoff"], label="Runoff")
plt.plot(df["Date"], df["Drain_Level"], label="Drain Level")
plt.legend()
plt.xticks(rotation=45)
plt.title("Runoff & Simulated Drain Level - Chennai 2020")
plt.show()

df = df.dropna().reset_index(drop=True)

print(df.shape)
df.head()

features = [
    "Rainfall",
    "Rain_3day",
    "Rain_7day",
    "Soil_Moisture",
    "Runoff",
    "Drain_Level"
]

X = df[features]
y = df["Stress_Index"]

split_index = int(len(df) * 0.8)

X_train = X.iloc[:split_index]
X_test  = X.iloc[split_index:]

y_train = y.iloc[:split_index]
y_test  = y.iloc[split_index:]

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=300,
    max_depth=6,
    random_state=42
)

model.fit(X_train, y_train)

from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

y_pred = model.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("RMSE:", rmse)
print("R2 Score:", r2)

import matplotlib.pyplot as plt
import pandas as pd

importances = pd.Series(model.feature_importances_, index=features)

importances.sort_values().plot(kind="barh")
plt.title("Feature Importance")
plt.show()